name: Auto Build
on: 
  workflow_dispatch:
  push:
    branches: [master,main]
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/auto-build2.yml'
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [master,main]

jobs:
  auto-build:
    name: Auto Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build mod
      uses: ./.github/actions/build

    - name: Publish mod
      uses: Graicc/actions-testing/.github/actions/publish@main
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
