name: Auto Build
on: 
  workflow_dispatch:
  push:
    branches: [master,main]
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/auto-build.yml'
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [master,main]


jobs:
  auto-build:
    name: Auto Build
    runs-on: windows-latest
    steps:
      # Build mod
    - uses: actions/checkout@v3
    - name: Build Mod
      uses: ./.github/actions/build

      # Upload the mod
    - name: Upload to GitHub
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      if: "${{ env.WEBHOOK_URL == '' }}" # If there is no webhook, upload to the action
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: Build
    - name: Upload to Discord
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      if: "${{ env.WEBHOOK_URL != '' }}" # If a webhook is supplied, use it instead
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/ChaoticWeg/discord.sh/master/discord.sh -o discord.sh
        ./discord.sh \
        --webhook-url="${{ secrets.WEBHOOK_URL }}" \
        --text '**${{github.actor}}** on **${{github.repository}}**(${{github.ref}}): *${{ github.event.head_commit.message }}*\n<https://github.com/${{github.repository}}/commit/${{github.sha}}>' \
        --file Build.zip
        