name: Download Game
on: 
  workflow_dispatch:
  push:

jobs:
  download:
    name: download
    runs-on: ubuntu-latest
    steps:
      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1.1.1
      - name: Download Gorilla Tag
        run: |
          steamcmd +@sSteamCmdForcePlatformType windows +login ${{secrets.STEAM_USERNAME}} ${{secrets.STEAM_PASSWORD}} +force_install_dir ~/gorillatag +app_update 1533390 +quit
      - name: List
        run: |
          ls
          ls -l ~/gorillatag
      - name: Upload files
        uses: tsickert/discord-webhook@v3.2.0
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK_URL}}
          filename: "~/gorillatag/Gorilla Tag_Data/Managed/Assembly-CSharp.dll"
      

