name: Publish Test
on: 
  workflow_dispatch:
  push:
    branches: [master,main]
    paths:
      - '.github/workflows/publish-test.yml'


jobs:
  publish:
    name: Publish Test
    runs-on: windows-latest
    steps:
    - name: Upload to Discord
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/ChaoticWeg/discord.sh/master/discord.sh -o discord.sh
        echo $COMMIT_MESSAGE
        echo "$(echo $COMMIT_MESSAGE | head -n 1)"
        ./discord.sh \
        --webhook-url="${{ secrets.WEBHOOK_URL }}" \
        --text "**${{github.actor}}** on **${{github.repository}}**(${{github.ref}}): *$(echo $COMMIT_MESSAGE | head -n 1)*\n<https://github.com/${{github.repository}}/commit/${{github.sha}}>" \
        