name: Make Release
on: 
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  release:    
    name: Make Release
    runs-on: windows-latest
    steps:
      # Build mod
    - uses: actions/checkout@v3

    - name: Build mod
      uses: ./.github/actions/my-build-action

    - uses: ./.github/actions/release
      with:
        tag: ${{ inputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        template: .github/templates/release.md
        human-name: Action Test
