name: Make Release Small
on: 
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  release:    
    name: Make Release
    runs-on: windows-latest
    steps:
      # Build mod
    - uses: actions/checkout@v3

    - uses: ./.github/actions/release
      with:
        template: .github/templates/release.md
