name: Test Release
on:
  release:
    types: [published]

jobs:
  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: printenv BODY > message.md
        env:
          BODY: ${{ github.event.release.body }}
      - run: sed -i 's/\r$//g' message.md
      - run: cat message.md