name: Test Release
on:
  release:
    types: [published]

jobs:
  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: echo ${{ github.event.release.body }} > message.md
      - run: cat message.md